"""Detection Decision Records (DDR) — governance layer for detection-as-code."""

from ddr.models.record import (
    AcceptRiskDecision,
    DDRRecord,
    Decision,
    DeprecateDecision,
    ElasticQueryRef,
    ElasticTarget,
    ElasticTuning,
    Evidence,
    EvidenceType,
    KqlM365DQueryRef,
    KqlM365DTarget,
    KqlM365DTuning,
    KqlSentinelQueryRef,
    KqlSentinelTarget,
    KqlSentinelTuning,
    Lifecycle,
    LifecycleStatus,
    LogSource,
    Provenance,
    RetirementReason,
    RuleRef,
    RuleSource,
    Scope,
    SigmaTarget,
    SigmaTuning,
    SplunkQueryRef,
    SplunkTarget,
    SplunkTuning,
    SuppressDecision,
    Target,
    Tuning,
)

__version__ = "0.8.0"
__spec_version__ = "0.8"

__all__ = [
    "AcceptRiskDecision",
    "DDRRecord",
    "Decision",
    "DeprecateDecision",
    "ElasticQueryRef",
    "ElasticTarget",
    "ElasticTuning",
    "Evidence",
    "EvidenceType",
    "KqlM365DQueryRef",
    "KqlM365DTarget",
    "KqlM365DTuning",
    "KqlSentinelQueryRef",
    "KqlSentinelTarget",
    "KqlSentinelTuning",
    "Lifecycle",
    "LifecycleStatus",
    "LogSource",
    "Provenance",
    "RetirementReason",
    "RuleRef",
    "RuleSource",
    "Scope",
    "SigmaTarget",
    "SigmaTuning",
    "SplunkQueryRef",
    "SplunkTarget",
    "SplunkTuning",
    "SuppressDecision",
    "Target",
    "Tuning",
]
